services:
  db:
    image: postgres:16
    container_name: petcare_postgres
    environment:
      POSTGRES_DB: petcare
      POSTGRES_USER: petcare_user
      POSTGRES_PASSWORD: petcare_password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: